### ISSUE TITLE
TDD question. Using patching with assert_called_with

### ISSUE THREAD

**Issue by alexcbacken** [pycabook/fileinfo#1]
Hello

I'm currently going through your book. It very good. 

I'm wondering if there is anyway to test for arguments when patching.
From your book we have the below test. I can make the test pass using two different versions of def get_info. please see below

The Test:

    @patch('os.path.getsize')
    @patch('os.path.abspath')
    def test_get_info(abspath_mock, getsize_mock):
        test_abspath = 'some/made/up/path'
        abspath_mock.return_value = test_abspath

        test_size = 1234
        getsize_mock.return_value = test_size

        filename = 'somefile.ext'
        original_path = '../{}'.format(filename)

        fi = FileInfo(original_path)

        assert fi.get_info() == (filename, original_path, test_abspath, test_size)

get_info version 1. passes test but is not what we want:

        def get_info (self):
            return (
                self.filename,
                self.original_path,
                os.path.abspath(self.filename),
                os.path.getsize(self.original_path)
                #line above should read : os.path.getsize(self.filename) 

get_info version 2. the one we want:

        def get_info (self):
            return (
                self.filename,
                self.original_path,
                os.path.abspath(self.filename),
                os.path.getsize(self.filename)#this is correct
            )

As os.path.getsize is hot swapped at runtime, we don't know if these arguments are correct.
An obvious solution would be to:

    abspath_mock.assert_called_with('self.filename')

But with this i get a not called AssertionError
Is this just something i need to be aware of? or is there a way to test arguments when using patching?
Any directions would be greatly appreciated.

**Comment by lgiordani** [comment]
Hi! Thanks for the question, a very good one.

You are right, that test might be improved. I think you just used the wrong code, this works for me

```
@patch('os.path.getsize')
@patch('os.path.abspath')
def test_get_info(abspath_mock, getsize_mock):
    filename = 'somefile.ext'
    original_path = '../{}'.format(filename)

    test_abspath = 'some/abs/path'
    abspath_mock.return_value = test_abspath

    test_size = 1234
    getsize_mock.return_value = test_size

    fi = FileInfo(original_path)
    assert fi.get_info() == (filename, original_path, test_abspath, test_size)
    getsize_mock.assert_called_with(filename)
```

It fails with `get_info` version 1 and passes with verison 2.

Your solution `abspath_mock.assert_called_with('self.filename')` has two errors:

1. You use `abspath_mock` instead of `getsize_mock`
2. You pass `'self.filename'` (which is a string!) while you want to pass the actual value that call should use, that is `filename` in the context of the `test_get_info` function.

I hope this helps! Feel free to continue the discussion is this is not clear, I'll leave this open just in case.

**Comment by alexcbacken** [comment]
That makes perfect sense.
I probably should have played around with the .assert_called_with() arguments a bit more.
Thanks a lot
